[package]
name = "base94"
version = "0.1.6"
edition = "2021"

[lib]
name = "_base94"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"
pyo3 = "0.23.4"
